[2024-01-31 09:15:22,724] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: etl_postgresql.get_data_covid scheduled__2024-01-29T23:00:00+00:00 [queued]>
[2024-01-31 09:15:22,730] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: etl_postgresql.get_data_covid scheduled__2024-01-29T23:00:00+00:00 [queued]>
[2024-01-31 09:15:22,730] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-01-31 09:15:22,730] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2024-01-31 09:15:22,730] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-01-31 09:15:22,738] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): get_data_covid> on 2024-01-29 23:00:00+00:00
[2024-01-31 09:15:22,741] {standard_task_runner.py:52} INFO - Started process 694 to run task
[2024-01-31 09:15:22,744] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'etl_postgresql', 'get_data_covid', 'scheduled__2024-01-29T23:00:00+00:00', '--job-id', '79', '--raw', '--subdir', 'DAGS_FOLDER/etl_dag.py', '--cfg-path', '/tmp/tmpgep_ni6m', '--error-file', '/tmp/tmpip5g0y2x']
[2024-01-31 09:15:22,745] {standard_task_runner.py:80} INFO - Job 79: Subtask get_data_covid
[2024-01-31 09:15:22,782] {task_command.py:369} INFO - Running <TaskInstance: etl_postgresql.get_data_covid scheduled__2024-01-29T23:00:00+00:00 [running]> on host d99f9e65d396
[2024-01-31 09:15:22,805] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1451, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1555, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 2202, in render_templates
    rendered_task = self.task.render_template_fields(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 1179, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 71, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 348, in _do_render_template_fields
    seen_oids,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 385, in render_template
    template = jinja_env.get_template(value)
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/environment.py", line 997, in get_template
    return self._load_template(name, globals)
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/environment.py", line 958, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 125, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 214, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: ./scripts/get_covid_data.sh
[2024-01-31 09:15:22,812] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=etl_postgresql, task_id=get_data_covid, execution_date=20240129T230000, start_date=20240131T091522, end_date=20240131T091522
[2024-01-31 09:15:22,821] {standard_task_runner.py:97} ERROR - Failed to execute job 79 for task get_data_covid (./scripts/get_covid_data.sh; 694)
[2024-01-31 09:15:22,839] {local_task_job.py:156} INFO - Task exited with return code 1
[2024-01-31 09:15:22,862] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
