[2024-02-01 11:52:01,965] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: etl_postgresql.aggregate_dim_table manual__2024-02-01T11:52:00.700808+00:00 [queued]>
[2024-02-01 11:52:01,973] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: etl_postgresql.aggregate_dim_table manual__2024-02-01T11:52:00.700808+00:00 [queued]>
[2024-02-01 11:52:01,973] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-02-01 11:52:01,974] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2024-02-01 11:52:01,974] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-02-01 11:52:01,984] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): aggregate_dim_table> on 2024-02-01 11:52:00.700808+00:00
[2024-02-01 11:52:01,987] {standard_task_runner.py:52} INFO - Started process 981 to run task
[2024-02-01 11:52:01,990] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'etl_postgresql', 'aggregate_dim_table', 'manual__2024-02-01T11:52:00.700808+00:00', '--job-id', '241', '--raw', '--subdir', 'DAGS_FOLDER/etl_dag.py', '--cfg-path', '/tmp/tmpdmobiu91', '--error-file', '/tmp/tmps9daenfb']
[2024-02-01 11:52:01,991] {standard_task_runner.py:80} INFO - Job 241: Subtask aggregate_dim_table
[2024-02-01 11:52:02,035] {task_command.py:369} INFO - Running <TaskInstance: etl_postgresql.aggregate_dim_table manual__2024-02-01T11:52:00.700808+00:00 [running]> on host 0cb2a3b23a40
[2024-02-01 11:52:02,097] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=etl_postgresql
AIRFLOW_CTX_TASK_ID=aggregate_dim_table
AIRFLOW_CTX_EXECUTION_DATE=2024-02-01T11:52:00.700808+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-02-01T11:52:00.700808+00:00
[2024-02-01 11:52:05,443] {logging_mixin.py:115} INFO - Successfully install sqlalchemy
[2024-02-01 11:52:08,451] {logging_mixin.py:115} INFO - Successfully install sqlalchemy
[2024-02-01 11:52:11,391] {logging_mixin.py:115} INFO - Successfully install pymysql
[2024-02-01 11:52:14,367] {logging_mixin.py:115} INFO - Successfully install sqlalchemy
[2024-02-01 11:53:29,412] {logging_mixin.py:115} INFO - An error occurred: (psycopg2.OperationalError) could not connect to server: Connection refused
	Is the server running on host "172.23.0.1" and accepting
	TCP/IP connections on port 5435?

(Background on this error at: http://sqlalche.me/e/14/e3q8)
[2024-02-01 11:53:29,412] {python.py:173} INFO - Done. Returned value was: end
[2024-02-01 11:53:29,430] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=etl_postgresql, task_id=aggregate_dim_table, execution_date=20240201T115200, start_date=20240201T115201, end_date=20240201T115329
[2024-02-01 11:53:29,450] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-02-01 11:53:29,467] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
