[2024-02-01 13:48:01,950] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: etl_postgresql.import_file_to_mysql manual__2024-02-01T13:48:01.368228+00:00 [queued]>
[2024-02-01 13:48:01,958] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: etl_postgresql.import_file_to_mysql manual__2024-02-01T13:48:01.368228+00:00 [queued]>
[2024-02-01 13:48:01,958] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-02-01 13:48:01,959] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2024-02-01 13:48:01,959] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-02-01 13:48:01,969] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): import_file_to_mysql> on 2024-02-01 13:48:01.368228+00:00
[2024-02-01 13:48:01,973] {standard_task_runner.py:52} INFO - Started process 3896 to run task
[2024-02-01 13:48:01,976] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'etl_postgresql', 'import_file_to_mysql', 'manual__2024-02-01T13:48:01.368228+00:00', '--job-id', '263', '--raw', '--subdir', 'DAGS_FOLDER/etl_dag.py', '--cfg-path', '/tmp/tmp3pe7ulhv', '--error-file', '/tmp/tmp8wd80l_w']
[2024-02-01 13:48:01,978] {standard_task_runner.py:80} INFO - Job 263: Subtask import_file_to_mysql
[2024-02-01 13:48:02,030] {task_command.py:369} INFO - Running <TaskInstance: etl_postgresql.import_file_to_mysql manual__2024-02-01T13:48:01.368228+00:00 [running]> on host 0cb2a3b23a40
[2024-02-01 13:48:02,111] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=etl_postgresql
AIRFLOW_CTX_TASK_ID=import_file_to_mysql
AIRFLOW_CTX_EXECUTION_DATE=2024-02-01T13:48:01.368228+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-02-01T13:48:01.368228+00:00
[2024-02-01 13:48:05,264] {logging_mixin.py:115} INFO - Successfully install pandas
[2024-02-01 13:48:08,736] {logging_mixin.py:115} INFO - Successfully install sqlalchemy
[2024-02-01 13:48:11,898] {logging_mixin.py:115} INFO - Successfully install pymysql
[2024-02-01 13:48:12,037] {python.py:173} INFO - Done. Returned value was: import to mysql
[2024-02-01 13:48:12,058] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=etl_postgresql, task_id=import_file_to_mysql, execution_date=20240201T134801, start_date=20240201T134801, end_date=20240201T134812
[2024-02-01 13:48:12,074] {local_task_job.py:221} WARNING - State of this instance has been externally set to success. Terminating instance.
[2024-02-01 13:48:12,078] {process_utils.py:129} INFO - Sending Signals.SIGTERM to group 3896. PIDs of all processes in the group: [3896]
[2024-02-01 13:48:12,079] {process_utils.py:80} INFO - Sending the signal Signals.SIGTERM to group 3896
[2024-02-01 13:48:12,079] {process_utils.py:75} INFO - Process psutil.Process(pid=3896, status='terminated', exitcode=0, started='13:48:01') (3896) terminated with exit code 0
