[2024-02-02 03:58:56,777] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: etl_postgresql.import_file_to_mysql scheduled__2024-02-01T00:05:00+00:00 [queued]>
[2024-02-02 03:58:56,783] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: etl_postgresql.import_file_to_mysql scheduled__2024-02-01T00:05:00+00:00 [queued]>
[2024-02-02 03:58:56,783] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-02-02 03:58:56,783] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2024-02-02 03:58:56,783] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-02-02 03:58:56,791] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): import_file_to_mysql> on 2024-02-01 00:05:00+00:00
[2024-02-02 03:58:56,793] {standard_task_runner.py:52} INFO - Started process 213 to run task
[2024-02-02 03:58:56,796] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'etl_postgresql', 'import_file_to_mysql', 'scheduled__2024-02-01T00:05:00+00:00', '--job-id', '292', '--raw', '--subdir', 'DAGS_FOLDER/etl_dag.py', '--cfg-path', '/tmp/tmpxo1rf4uo', '--error-file', '/tmp/tmptgkzn05w']
[2024-02-02 03:58:56,797] {standard_task_runner.py:80} INFO - Job 292: Subtask import_file_to_mysql
[2024-02-02 03:58:56,826] {task_command.py:369} INFO - Running <TaskInstance: etl_postgresql.import_file_to_mysql scheduled__2024-02-01T00:05:00+00:00 [running]> on host c3bb523480bf
[2024-02-02 03:58:56,864] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=etl_postgresql
AIRFLOW_CTX_TASK_ID=import_file_to_mysql
AIRFLOW_CTX_EXECUTION_DATE=2024-02-01T00:05:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-02-01T00:05:00+00:00
[2024-02-02 03:58:59,123] {logging_mixin.py:115} INFO - Successfully install pandas
[2024-02-02 03:59:01,578] {logging_mixin.py:115} INFO - Successfully install sqlalchemy
[2024-02-02 03:59:05,558] {logging_mixin.py:115} INFO - Successfully install pymysql
[2024-02-02 03:59:15,603] {logging_mixin.py:115} INFO - An error occurred: (pymysql.err.OperationalError) (2003, "Can't connect to MySQL server on '172.24.0.1' (timed out)")
(Background on this error at: http://sqlalche.me/e/14/e3q8)
[2024-02-02 03:59:15,604] {python.py:173} INFO - Done. Returned value was: end
[2024-02-02 03:59:15,654] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=etl_postgresql, task_id=import_file_to_mysql, execution_date=20240201T000500, start_date=20240202T035856, end_date=20240202T035915
[2024-02-02 03:59:15,684] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-02-02 03:59:15,709] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
