[2024-02-01 11:35:56,713] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: etl_postgresql.import_file_to_mysql scheduled__2024-01-31T23:00:00+00:00 [queued]>
[2024-02-01 11:35:56,719] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: etl_postgresql.import_file_to_mysql scheduled__2024-01-31T23:00:00+00:00 [queued]>
[2024-02-01 11:35:56,719] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-02-01 11:35:56,720] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2024-02-01 11:35:56,720] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-02-01 11:35:56,729] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): import_file_to_mysql> on 2024-01-31 23:00:00+00:00
[2024-02-01 11:35:56,731] {standard_task_runner.py:52} INFO - Started process 221 to run task
[2024-02-01 11:35:56,734] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'etl_postgresql', 'import_file_to_mysql', 'scheduled__2024-01-31T23:00:00+00:00', '--job-id', '216', '--raw', '--subdir', 'DAGS_FOLDER/etl_dag.py', '--cfg-path', '/tmp/tmph046c_s0', '--error-file', '/tmp/tmpxq0r3bp3']
[2024-02-01 11:35:56,735] {standard_task_runner.py:80} INFO - Job 216: Subtask import_file_to_mysql
[2024-02-01 11:35:56,771] {task_command.py:369} INFO - Running <TaskInstance: etl_postgresql.import_file_to_mysql scheduled__2024-01-31T23:00:00+00:00 [running]> on host 0cb2a3b23a40
[2024-02-01 11:35:56,817] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=etl_postgresql
AIRFLOW_CTX_TASK_ID=import_file_to_mysql
AIRFLOW_CTX_EXECUTION_DATE=2024-01-31T23:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-01-31T23:00:00+00:00
[2024-02-01 11:35:59,708] {logging_mixin.py:115} INFO - Successfully install pandas
[2024-02-01 11:36:02,885] {logging_mixin.py:115} INFO - Successfully install sqlalchemy
[2024-02-01 11:36:06,200] {logging_mixin.py:115} INFO - Successfully install pymysql
[2024-02-01 11:36:16,259] {logging_mixin.py:115} INFO - An error occurred: (pymysql.err.OperationalError) (2003, "Can't connect to MySQL server on '172.23.0.1' (timed out)")
(Background on this error at: http://sqlalche.me/e/14/e3q8)
[2024-02-01 11:36:16,261] {python.py:173} INFO - Done. Returned value was: end
[2024-02-01 11:36:16,296] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=etl_postgresql, task_id=import_file_to_mysql, execution_date=20240131T230000, start_date=20240201T113556, end_date=20240201T113616
[2024-02-01 11:36:16,327] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-02-01 11:36:16,352] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
